name: Deploy Docs
on:
  push:
    branches:
      - master
    paths:
      - 'packages/foo-api-docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      S3_DIRECTORY_SYNC_ACCESS_KEY_ID: ${{ secrets.S3_DIRECTORY_SYNC_ACCESS_KEY_ID }}
      S3_DIRECTORY_SYNC_BUCKET: ${{ secrets.S3_DIRECTORY_SYNC_BUCKET }}
      S3_DIRECTORY_SYNC_SECRET_ACCESS_KEY: ${{ secrets.S3_DIRECTORY_SYNC_SECRET_ACCESS_KEY }}
      S3_DIRECTORY_SYNC_LOCAL_DIRECTORY: ${{ secrets.S3_DIRECTORY_SYNC_LOCAL_DIRECTORY }}
      S3_DIRECTORY_SYNC_STRICT: ${{ secrets.S3_DIRECTORY_SYNC_STRICT }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          scope: '@foo-software'
      - name: Install
        run: |
          cd packages/foo-api-docs
          npm install
      - name: Build
        run: |
          cd packages/foo-api-docs
          npm run build
      - name: Deploy
        run: |
          cd packages/foo-api-docs
          npm run deploy:s3
