name: Publish
on:
  push:
    branches:
      - master
    paths:
      - 'packages/foo-api-client/**'
      - 'packages/foo-api-docs/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          scope: '@foo-software'
      - name: Install
        run: |
          npm install
          npm run lerna -- bootstrap --hoist
      - name: Publish Packages
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN  }}' > ${{ github.workspace }}/.npmrc
          node packages/foo-api-ci-tools/dist/bin/config-git.js
          node packages/foo-api-ci-tools/dist/bin/publish-packages.js
