name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          scope: '@foo-software'
      - name: Use stable npm version
        run: npm install -g npm@9.9.0
      - name: Install
        run: |
          npm ci
          npm run lerna -- bootstrap --hoist
      - name: Publish Packages
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN  }}' > ${{ github.workspace }}/.npmrc
          node packages/foo-api-ci-tools/dist/bin/config-git.js
          node packages/foo-api-ci-tools/dist/bin/publish-packages.js
